### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by anon97945** [Qwerty-Space/AntiDeletedAccountsBot#1]
Hello,

Why there is a logging module, what does it log?
Why does the bot has read permission from bothfather?

Regards

**Comment by Qwerty-Space** [comment]
All it legs is the user ID, group ID, and username of the person who triggered a function of the bot, for debugging purposes, so that I can find out what message caused something to break. 

The bot will only clear deleted accounts when a new message is sent to a group, and has a cooldown of one hour.

**Comment by anon97945** [comment]
Ah okay, thank you.

**Comment by KlausDevWalker** [comment]
Would it be possible, if it doesn't affect the bot performance, to allow some manual use? A cooldown on that function smaller than the default would be nice :)

**Comment by Qwerty-Space** [comment]
Not really relevant to this issue.  Don't comment on irrelevant issues in the future.

To answer your question, no.  I might add a command only I can use to trigger updates in other groups though for debugging purposes
