### ISSUE TITLE
Question: How to run the bot stably??

### ISSUE THREAD

**Issue by RomanGoddess** [Qwerty-Space/AntiDeletedAccountsBot#4]
I tried running the commands on termux but found out the bot goes off after a while of starting bot.py. can u please guide me or hint me on what to do to make it stable

**Comment by Qwerty-Space** [comment]
I can't help without an error. Try running `pip install --user -r requirements.txt` 
Then run `python bot.py` and show me the output

**Comment by RomanGoddess** [comment]
> I can't help without an error. Try running `pip install --user -r requirements.txt`
> Then run `python bot.py` and show me the output

![Screenshot_20201107_203615](https://user-images.githubusercontent.com/53878781/98449993-eb083180-2138-11eb-9e64-360cbf9a4bbc.jpg)


But after closing termux and an hour passes bot becomes dead until i run commands on termux once again

**Comment by Qwerty-Space** [comment]
Sounds like an Android issue.  
![image](https://user-images.githubusercontent.com/6967592/98450503-1557f000-2135-11eb-8ee1-b95ce035830b.png)

Tapping this in the Termux notification should stop it from being closed by android's battery saving measures.  However your device will not enter deep-sleep.

https://wiki.termux.com/wiki/Termux-wake-lock

Closing this issue because it is not an issue with ADAb.
